# Dependencies
markdown:         rdiscount
highlighter:         pygments

# Permalinks
permalink:        /words/:year/:month/:day/:title

# Setup
title:            Li Yishan
tagline:          '[ write words ]'
description:      '一二三·生万物'
url:              http://write.liyishan.me

# Contact
author : 'Li Yishan'
name : 'Yishan'
email :  'mail # liyishan.me'
url :  'https://weibo.com/costi'

paginate :         6

# Custom vars
comments :
  provider : duoshuo
  duoshuo :
    short_name : liyishan
