# Dependencies
markdown:         rdiscount
highlighter:         pygments

# Permalinks
permalink:        /words/:year/:month/:day/:title

# Setup
title:            Li Yishan
tagline:          '[ write words ]'
description:      'writing mood, air and everything else.'
url:              http://write.liyishan.me

# Contact
author : liyishan
name : 'Yishan'
email :  mail@liyishan.me
url :  https://weibo.com/costi

paginate :         6

# Custom vars
comments :
  provider : duoshuo
  duoshuo :
    short_name : liyishan

version :        0.0.1
