# Dependencies
markdown:         rdiscount
highlighter:         pygments

# Permalinks
permalink:        /blog/:year/:month/:day/:title

# Setup
title:            Li Yishan
tagline:          '[ words ]'
description:      'writing mood & air'
url:              http://write.liyishan.me

# Contact
author: liyishan
name: 'Yishan'
email:  mail@liyishan.me
url:  https://weibo.com/costi

paginate:         6

# Custom vars
version:        0.0.1
